config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: 'users/sessions' }
  root to: "dashboards#index"
  resources :dashboards, only: [:index]
  resources :lists do
    resources :tasks, only: [:create, :new]
    post 'ocr', on: :member
  end
  resources :tasks, only: [:update, :destroy, :edit]
  resources :reminders, only: [:new, :edit, :index, :update, :destroy, :create] do
    post 'ocr', on: :collection
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  enum category: { autre: 0, courses: 1, vacances: 2, maison: 3, administratif: 4, enfants: 5 }


  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :name, :category, presence: true

  def order_by_done_tasks
    tasks.order(done: :asc)
  end

  # private

  # def set_content
  #   OcrListJob.perform_later(self)
  # end

end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :user

  validates :description, presence: true, on: :update
  validates :end_date, presence: true, on: :update

  scope :order_by_date, -> { order(:end_date).where("DATE(end_date) >= ?", Date.current) }

  # def order_by_hour_reminders
  #   reminders.order(DateTime.hour: :asc)
  # end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :label, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists
  has_many :reminders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @list = List.new
    @last_lists = current_user.lists.last(3)
    @reminders = current_user.reminders.order(:end_date).where("DATE(end_date) = ?", Date.current)
  end
end

app/controllers/lists_controller.rb
require "open-uri"

class ListsController < ApplicationController

  def index
    @lists = current_user.lists
  end

  def new
    @list = List.new
    @tasks = Task.new
  end

  def show
    @list = List.find(params[:id])
    @task_new = Task.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
     if @list.save
       redirect_to list_path(@list)
     else
       render "dashboards/index", status: :unprocessable_entity
     end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to list_path, status: :see_other
  end

  def ocr
    @list = List.find(params[:id])
    Turbo::StreamsChannel.broadcast_update_to(
      "list_#{@list.id}",
      target: "loader",
      partial: "shared/loader")

    photo = encode_image(params[:ocr][:temp_photo])
    OcrListJob.perform_later(photo, @list)
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  private

  def encode_image(photo)
    file_content = File.read(photo.tempfile)
    Base64.strict_encode64(file_content)
  end

  def list_params
    params.require(:list).permit(:name, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reminders_controller.rb
require "open-uri"

class RemindersController < ApplicationController

  def index
    @reminders = current_user.reminders.order_by_date
    @reminder = Reminder.new
  end

  def new
    @reminder = Reminder.new
  end

  def show
    @reminder = Reminder.find(params[:id])
    @hour = @reminder.end_date.hour
    @minutes = @reminder.end_date.min
  end

  def create
    @reminder = Reminder.new(reminder_params)
    unless reminder_params[:end_date].empty? && params[:hours].empty?
      end_date = DateTime.parse("#{reminder_params[:end_date]} #{params[:hours]}")
      @reminder.end_date = end_date
    end
    @reminder.user = current_user
    if @reminder.save
      redirect_to reminders_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @reminder = Reminder.find(params[:id])
    @hour = @reminder.end_date.hour
    @minutes = @reminder.end_date.min
  end

  def update
    @reminder = Reminder.find(params[:id])
    if @reminder.update(description: params[:reminder][:description], end_date: DateTime.parse("#{params[:reminder][:end_date]} #{params[:hours]}"))
      redirect_to reminders_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @reminder = Reminder.find(params[:id])
    @reminder.destroy
    redirect_to reminders_path
  end

  def ocr
    @reminder = Reminder.create!(user: current_user)
    Turbo::StreamsChannel.broadcast_append_to(
      "reminder-index",
      target: "loader",
      partial: "shared/loader")

    OcrReminderJob.perform_now(@reminder, encode_image(params[:ocr][:temp_photo]), current_user)
  end
  private

  def reminder_params
    params.require(:reminder).permit(:description, :end_date, :hours)
  end

  def encode_image(photo)
    file_content = File.read(photo.tempfile)
    Base64.strict_encode64(file_content)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:update]

  def create
    @list = List.find(params[:list_id])
    @task = Task.new(task_params)
    @task.list = @list
    if @task.save
      redirect_to list_path(@list)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @list = @task.list
    @task.update(task_params)
    redirect_to list_path(@list)
  end

  def destroy
    @task = Task.find(params[:id])
    @list = @task.list
    @task.destroy
    respond_to do |format|
      format.html { redirect_to list_path(@list)}
      format.turbo_stream
    end

  end

  private

  def task_params
    params.require(:task).permit(:label, :done)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  after_action :remove_notice

  private

  def remove_notice
    flash.discard(:notice) #http://api.rubyonrails.org/v5.1/classes/ActionDispatch/Flash/FlashHash.html#method-i-discard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def image_category(category)
    return "#{category}.png"
  end
end

app/views/dashboards/_list_card.html.erb
<%=link_to list_path(list), class: "col-6 p-0 text-decoration-none" do %>
      <div class= "list-card-dashboard" style="background-image: url(<%= image_path(image_category(list.category)) %>)">
        <p><%= list.name  %></p>
      </div>
<% end %>

app/views/dashboards/_modal.html.erb
<div class="modal" tabindex="-1" id="listModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Créer une nouvelle liste </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, label: 'Nom de la liste' %>
          <%= f.select :category, options_for_select(List.categories.map {|key, value| [key.capitalize, key]}), class: 'select-form' %>
         <%= f.button :submit, 'Valider', class: 'validate-button btn btn-dark mb-3 fw-bold mt-3' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_reminder_card.html.erb
<%=link_to edit_reminder_path(reminder), class: "col-6 p-0 text-decoration-none" do %>
  <div class= "reminder-card-dashboard">
    <div class="card-calendar d-flex">
      <div class="d-flex flex-column">
        <div class="calendar-header">
          <span class="month"><%= Date.today.strftime("%b").upcase %></span>
        </div>
        <div class="calendar-body">
          <span class="date"><%= Date.today.strftime("%d") %></span>
        </div>
      </div>
      <div class="d-flex flex-column my-2 ms-2">
        <h5><%= reminder.description %></h5>
        <p><%= reminder.end_date.strftime("%Hh%M") %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboards/index.html.erb
<div class="container">

  <div class="d-flex align-items-baseline">

    <div class="col-6 text-left mt-2">
      <h2><b>Listes</b></h2>
    </div>

    <div class="col-6 text-right">
      <div class= "voir-plus-lists d-flex align-items-baseline gap-2">
      <p class="mb-0"><%=link_to "Voir plus...", lists_path%></p>
      <i class="fa-solid fa-angles-right"></i>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-6 p-0" style="cursor:pointer;" data-bs-toggle="modal" data-bs-target="#listModal">
      <div class="list-card-dashboard" >
        <div>Ajouter<br>une liste</div>
        <i class="fa-solid fa-circle-plus color mt-3"></i>
      </div>
    </div>
    <% @last_lists.each do |list| %>
      <%=render "list_card", list: list %>
    <% end %>
  </div>

</div>


<div class="container">

  <div class="d-flex align-items-baseline mt-3">

    <div class="col-7 text-left mt-4">
      <h2><b>Rappels du jour</b></h2>
    </div>

    <div class="col-4 text-right">
      <div class="voir-plus-reminders d-flex align-items-right gap-2 voir-plus-reminders-background">
      <p class="mb-0"><%=link_to "Voir plus...", reminders_path %></p>
      <i class="fa-solid fa-angles-right"></i>
      </div>
    </div>

  </div>



  <div class="row">
    <div class="col-12 p-0" style="cursor:pointer;" data-bs-toggle="modal" data-bs-target="#reminderModal">
          <% @reminders.each do |reminder| %>
          <%=render "reminder_card", reminder: reminder %>
          <% end %>
    </div>
  </div>

</div>

<%= render 'dashboards/modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task-it</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,600;1,600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital@0;1&display=swap" rel="stylesheet">


   <script src="https://kit.fontawesome.com/45e38e596f.js" crossorigin="anonymous"></script>

  </head>

  <body><%= render "shared/navbar" %>
        <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/lists/_list_tasks.html.erb
<% list.order_by_done_tasks.each do |task| %>
  <%= render 'tasks/task', task: task %>
<% end %>

app/views/lists/_loader.html.erb
<div id="loader d-none">
  <div id="shadow"></div>
  <div id="box"></div>
</div>
<%# <h4>Loader #6</h4> %>

app/views/lists/edit.html.erb
<h2>hello</h2>

app/views/lists/index.html.erb
  <div class= "my-title">
    <h2>Mes listes</h2>
  </div>
    <ul><% @lists.each do |list| %></ul>
      <%= link_to list_path(list), class:"lists-card-link" do %>
        <div class="lists-card-index d-flex justify-content">
          <%= list.name %>
          <div class="trash d-flex">
            <%= link_to list_path(list),
                data: {
                  turbo_method: :delete,
                } do %>
                <i class="fa-regular fa-trash-can mt-1 trash-btn" style="color: $black;"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>

app/views/lists/show.html.erb
<div class="container">
  <%= turbo_stream_from dom_id(@list) %>
  <div id="loader"></div>
  <div class="list-card-product" style="background-image: url(<%= image_path(image_category(@list.category)) %>)">
    <div class="row">
      <div class="" data-controller="edit">
        <div class="d-flex justify-content-between my-3"data-edit-target="listTitle">
          <h2 class="flex-grow-1 text-center" > <%= @list.name %></h2>
          <i class="fa-solid fa-pen my-2 me-3" data-action="click->edit#addOnClick"></i>
        </div>
          <%= simple_form_for @list, html: { class: "d-none"}, data: { edit_target: "editForm" } do |f| %>
        <div class="d-flex justify-content-between mx-2">
          <div class="flex-grow-1 text-center">
            <%= f.input_field :name, placeholder: (@list.name), class: "list-name-input" %>
            <%= button_tag type: "submit", class: "button-validate" do %>
            <i class="fa-solid fa-check"></i>
          </div>
          <% end %>
        </div>
      </div>
        <% end %>
        <div id="<%= dom_id(@list) %>-tasks">
          <%= render "list_tasks", list: @list %>
        </div>
          <%= simple_form_for [@list, @task_new] do |f| %>
            <%= f.input_field :label, placeholder: ' Ajouter un élément', class: "add-task-input"%>
            <%= button_tag type: "submit", class: "button-validate" do %>
              <i class="fa-solid fa-check"></i>
            <% end %>
          <% end %>

        <div class="col-12 text-center mt-4">
           <%# input pour OCR %>
          <%= simple_form_for :ocr, url: ocr_list_path(id: @list.id), method: :post, html: { multipart: true, data: { controller: "submit-photo"} } do |f| %>

              <%= f.input :temp_photo, as: :file, input_html: { id: "fileInput", data: {action:"change->submit-photo#submitFormPhoto"}}, wrapper_html: { class: "d-none" } %>

           <label for="fileInput" style="cursor: pointer;">
             <%=image_tag "scan-black.png", class:"mb-3", alt: "scan", width: "30" %>
           </label>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reminders/_reminder_calendar.html.erb
<div class="reminders-card-index d-flex">

  <div class="d-flex flex-column">
    <div class="calendar-header">
      <span class="month"><%= reminder.end_date.strftime("%b").upcase %></span>
    </div>
    <div class="calendar-body">
        <span class="date"><%= reminder.end_date.strftime("%d") %></span>
    </div>
  </div>

  <div class="d-flex flex-column my-2 ms-2">
    <h5><%= link_to reminder.description,edit_reminder_path(reminder), class:"reminders-card-link" %></h5>
    <p><%= link_to reminder.end_date.strftime("%Hh%M"),edit_reminder_path(reminder) %></p>
  </div>

  <div class="trash-2 d-flex flex-column justify-content-center">
    <%= link_to reminder_path(reminder), data: { turbo_method: :delete } do %>
    <i class="fa-regular fa-trash-can trash-btn me-2" style="color: #FFFFFF;"></i>
    <% end %>
  </div>

</div>

app/views/reminders/_reminders.html.erb
<% reminders.each do |reminder| %>
    <%= render "reminders/reminder_calendar", reminder: reminder %>
<% end %>

app/views/reminders/edit.html.erb
<div class="container align-items-center flex-column d-flex reminder-create">
    <h1 class="title-reminder"><%= @reminder.description %></h1>
    <%= simple_form_for(@reminder) do |f| %>
      <%= f.input :description, :label => false, input_html: {style: "color: black"}%>
      <%= f.input :end_date, as: :string, :label => "Date *", input_html:{data: { controller: "flatpickr", flatpickr_end_date_value: @reminder.end_date.iso8601(3) }}%>
      <%= f.input :hours,  as: :string, :label => "Heure *" do %>
        <%= text_field_tag "hours", "#{@hour}:#{@minutes}", class: "w-100 px-3", style:"height:40px", data: {controller: "timepicker", timepicker_hour_value: @hour, timepicker_minutes_value: @minutes } %>
      <% end %>
      <div class="d-flex justify-content-center">
        <%= f.submit "Mettre à jour", class: "btn validate-button"%>
      </div>
    <% end %>
</div>

app/views/reminders/index.html.erb
<%= turbo_stream_from "reminder-index" %>
<div id="loader"></div>

<div class="d-flex reminder-align">
  <div class="col-8 text-left my-title my-4">
    <h2 class="mb-0">Mes rappels</h2>
  </div>

  <%# input pour OCR %>
  <%= simple_form_for :ocr, url: ocr_reminders_path(id: @reminder.id), method: :post, html: { multipart: true, data: { controller: "submit-photo"} } do |f| %>
    <%= f.input :temp_photo, as: :file, input_html: { id: "fileInput", capture: "environment", data: {action:"change->submit-photo#submitFormPhoto"}}, wrapper_html: { class: "d-none" } %>
    <label for="fileInput" style="cursor: pointer;">
      <%=image_tag "qr-code.png", alt: "scan", width: "30", class: "ms-3" %>
    </label>
  <% end %>
    <a class="btn" href="<%= new_reminder_path(@reminder) %>"><i class="fa-solid fa-circle-plus fa-2x ms-2"></i></a>
  </div>

<div id="reminder-list">
  <%= render "reminders", reminders: @reminders %>
</div>

app/views/reminders/new.html.erb
<div class="container align-items-center flex-column d-flex reminder-create">
    <h2 class="title-reminder">Créer un nouveau rappel</h2>
    <%= simple_form_for(@reminder) do |f| %>
      <%= f.input :description, placeholder: "Nom du rappel", :label => false, input_html: {style: "color: black"}%>
      <%= f.input :end_date, as: :string, :label => "Date *", input_html: {data: {controller: "flatpickr" } }%>
      <%= f.input :hours,  as: :string, :label => "Heure *" do %>
        <%= text_field_tag "hours", "#{@hour}:#{@minutes}", class: "w-100 px-3", style:"height:40px", data: {controller: "timepicker", timepicker_hour_value: @hour, timepicker_minutes_value: @minutes } %>
      <% end %>
      <div class="d-flex justify-content-center">
        <%= f.submit "Valider", class: "btn validate-button"%>
        </div>

    </div>
    <% end %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_loader.html.erb
<div id="loader-overlay">
  <div id="loader">
    <div id="shadow"></div>
    <div id="box"></div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">

  <!--<div class="container-fluid">-->
  <div class="col-12 d-flex justify-content-between">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-bars fa-xl me-3" style="color: #E6C768", width="80"></i>
    </button>

    <%= link_to root_path, class: "navbar-brand" do %>
    <%#=link_to list_path(list), class: "col-6 p-0 text-decoration-none" do %>
    <%=image_tag "logo-t4-ter.png", alt: "logo", width: "35" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-user fa-xl user-icon" style="color: #E6C768", width="80"></i>
    </button>

  </div>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav navbar-text-decoration align-items-center">
    <% if user_signed_in? %>
      <li><%= link_to "Mes listes", lists_path, class: "dropdown-item" %></li>
      <li><%= link_to "Mes rappels", reminders_path, class: "dropdown-item" %></li>
      <li><%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
    <% else %>
      <li class="nav-item">
      </li>
    <% end %>
    </ul>
  </div>

</nav>

app/views/tasks/_form.html.erb
<%= simple_form_for task do |f| %>
  <%= f.input_field :label, class:%>
  <%= button_tag type: "submit", class: "button-validate" do %>
    <i class="fa-solid fa-check"></i>
  <% end %>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id(task) %>">
  <%= turbo_frame_tag task do %>
    <%= simple_form_for task, data: { controller: "submit-task" } do |f| %>
      <div class="d-flex mx-3">
        <div class="me-auto p-1">
          <div class="cross-out">
            <%= f.input :done, as: :boolean, label: task.label, input_html: {data: {action: "change->submit-task#submitOnChange"}} %>
          </div>
        </div>
        <div class="mb-2">
          <%= link_to edit_task_path(task) do %>
            <i class="fa-solid fa-pen me-3"></i>
          <% end %>
        </div>
        <div class="">
          <%= link_to task_path(task),
            data: {
              turbo_method: :delete,
            } do %>
            <i class="fa-regular fa-trash-can trash-btn" style="color: $black;"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove "task_#{@task.id}" %>

app/views/tasks/edit.html.erb
<%= turbo_frame_tag @task do %>
  <%= render "form", task: @task %>
<% end %>